app:
  config:
    keycloak:
      url: http://keycloak:28080/auth
      realm: micro-dev

server:
  port: 9099
spring:
  main :
    web-application-type: reactive
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
            authorization-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
            user-name-attribute: preferred_username
            user-info-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
            user-info-authentication-method: header
        registration:
          micro-dev-client:
            provider: keycloak
            client-id: micro-dev-client
            client-secret: Zg2QXXWliYwiCQTPPDDYImHYkRbNdlEf
            authorization-grant-type: authorization_code
            redirect-uri: http://keycloak:28080/oauth2/code/keycloak
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
  ##GATEWAY CONFIGURATIONS
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        ## Customer service
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/**
          filters:
            - StripPrefix=1
        ## Auth service
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
